name: Start-up
on: push
jobs:
  load-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          RESTAPIKEY: ${{ secrets.RESTAPIKEY }}
          BRANCH: gh-pages
          FOLDER: dist
