name: Start-up
on: push
jobs:
  load-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          RESTAPIKEY: ${{ secrets.RESTAPIKEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages 
          folder: build
